spring:
  profiles: server1
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.206.16:8764/eureka/
    registerWithEureka: false
    fetchRegistry: false
  
---
spring:
  profiles: server2
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.206.16:8763/eureka/
    registerWithEureka: false
    fetchRegistry: false
  
 
      

