spring:
  profiles: server1
server:
  port: 8761
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.0.2.15:8762/eureka/
    registerWithEureka: false
    fetchRegistry: false

---
spring:
  profiles: server2
server:
  port: 8762
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.0.2.15:8761/eureka/
    registerWithEureka: false
    fetchRegistry: false

  
 
      

