spring:
  profiles: server1
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.0.2.15:8764/eureka/
    registerWithEureka: false
    fetchRegistry: false
  
---
spring:
  profiles: server2
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.0.2.15.16:8763/eureka/
    registerWithEureka: false
    fetchRegistry: false
  
 
      

