spring:
  profiles: server1
server:
  port: 8761
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://192.168.56.101:8761/eureka/
    registerWithEureka: false
    fetchRegistry: false
  

